---
title: "Understanding Studies"
subtitle: "Sampling"
author: "Dr. Dogucu"
date: "Week 3"
output: 
  xaringan::moon_reader:
    css: slide-styles.css
      
---

layout: true
  
<div class="my-header"></div>

<div class="my-footer"> 
 Copyright &copy; <a href="https://mdogucu.ics.uci.edu">Dr. Mine Dogucu</a>. All Rights Reserved.</div> 

---

## Research question

Do UCI students who exercise regularly have higher GPA?

---

## Population

Each research question aims to examine a __population__. 

Population for this research question is UCI students.


---

## Survey

- Do you exercise at least once every week?

- What is your GPA?

---

## Sampling

When it is impossible or costly to get information from all of the __population__ we take a __sample__. 

Since it would be almost impossible to give the survey to ALL UCI students, we can give it to a sample of students. 

---

## Convenience Sampling

- Stand in front of Langson Library
- Give the survey to 100 UCI students

This could introduce __bias__. It is possible that those in front of the library

- may study more and thus may have higher GPA.
- may be more active than those who study at home/dorm.

---

## Simple Random Sample

The goal is to have a sample that is __representative__ of the population.

We can use simple random sampling to select the sample. Using simple random sampling technique anybody in the population who has an equal chance of being selected to the sample. 

[Random Number Generator](https://www.google.com/search?channel=cus2&client=firefox-b-1-d&q=random+number+generator)



---

## Simple Random Sample

The researcher can 
- reach out to the registrar to get student emails. 
- randomly select 100 students.
- email them the survey

All of the 100 selected students respond.

Population: All UCI students  
Sample: 100 students who have responded

---

## Nonresponse Bias

It is unlikely that 100 students will respond. Assume that 86 respond. 

It is possible that those 14 who did not respond

- may be busy exercising and did not have the time to respond.
- may be busy studying and did not have the time to respond. 

This kind of bias is called __nonresponse bias__.

---

## Example 

An Anteater scientist is interested in counting the number of different species of bacteria in San Diego Creek. She takes a bucket of water from San Diego Creek and counts the different specifies of bacteria. The bacteria in the bucket make up the __sample__ and the bacteria in San Diego Creek make up the __population__. Note that this is not a simple random sample!

---


## Example

Customer Satisfaction Survey [Example](https://www.happy-or-not.com/en/smiley-terminal/)

The intent is to get opinion on all customers (population). 

The sample is based on self-selection. Those who want to provide opinion provide it. Not a random sample!

---

## Practice

A cell phone factory wants to do quality control of their products to ensure that their customers do not get malfunctioning products. They randomly select 3% of the phones that they produce and manually check if there are any problems or not. All the cell phones in the world make up the population and the cell phones that this factory produces make up the sample. True or false?

---

## Is it really random sampling? 

[Juke box](img/jukebox.png)  

---

## Notation

<table align ="center">

<thead>
<th> </th>
<th>Sample Statistic</th>
<th>Population Parameter</th>
</thead>

<tr>
<td>Mean</td>
<td> x&#772; </td>
<td> &mu;</td>

</tr>

<tr>
<td> Standard Deviation </td>
<td> s </td>
<td> &sigma;</td>

</tr>

<tr>
<td> Variance </td>
<td> s<sup>2</sup> </td>
<td> &sigma;<sup>2</sup></td>

</tr>

<tr> 
<td>Proportion</td>
<td>p</td>
<td>&pi;</td>

</tr>


</table>

As you may recall from previous week, sample size is denoted by $n$.
